version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASSWORD   # Change to your chosen root password
      MYSQL_DATABASE: web-db
      MYSQL_USER: web-user
      MYSQL_PASSWORD: USERPASSWORD        # Change to your chosen root password
    volumes:
        - mysql_data:/var/lib/mysql
    ports:
        - 3306:3306
  
  web:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: PHP.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      
volumes:
  mysql_data: {}
